name: Build SMPlayer on Mac OS
env:
  mplayer-url: https://github.com/smplayer-dev/mplayer/releases/download/v1.4-71/mplayer.tar.bz2

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: packages/smplayer

      - name: Get version
        run: |
            cd packages/smplayer
            ./get_version.sh
            VERSION=`cat version`-macos
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install build dependencies
        run: brew install create-dmg

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          host: 'mac'

      - name: Compile
        run: |
            cd packages/smplayer
            ./compile_mac.sh

      - name: Install mplayer
        run: |
            wget ${{ env.mplayer-url }}
            tar -xvf mplayer.tar.bz2 -C packages/smplayer/package/SMPlayer.app --strip-components=1

      - name: Create dmg
        run: |
            cd packages/smplayer
            ./create_dmg,sh
            ls -l package/

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-${{env.VERSION}}
          path: packages/smplayer/package/*.dmg

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./packages/smplayer/package/*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
