name: Build Windows 64-bit

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_mingw81
          #tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'
          tools: 'tools_mingw,qt.tools.win64_mingw810'

      - name: Build smplayer
        run: |
            .\getrev.cmd
            cd src
            lrelease smplayer.pro
            qmake
            mingw32-make -j4
