name: Build SMPlayer on Windows with MSVC

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build smplayer
        run: |
            .\getrev.cmd
            cd src
            lrelease smplayer.pro
            qmake
            nmake
            
